name: numda
version: 0.0.2
description: numeric library for dart (just like numpy)
repository: https://github.com/ccc-dart/numda
publish_to: https://pub.dev/
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  sprintf: ^4.0.2
  test: ^1.15.3
